LET A = 5
LET B = 10
LET C = A + B
PRINT C
PRINT "SUM OF A AND B IS"
PRINT A + B
IF A > B THEN IF C < D THEN PRINT "UM" ELSE PRINT "DOIS" ELSE PRINT "TRES"
IF A THEN IF B THEN PRINT "X"
IF A THEN IF B THEN PRINT "X" ELSE PRINT "Y"
FOR I = 1 TO 10
PRINT I
NEXT I
FOR I = 1 TO 9 STEP 2
PRINT A + B
NEXT I
FOR I = 1 TO 10
PRINT A + B
A = A + 1
NEXT I
